### ISSUE TITLE
Reverting Back (Android Studio)

### ISSUE THREAD

**Issue by Rohit-554** [Rohit-554/QuizApp_TestSkills#1]
There is a issue with this app , When someone selects/clicks a option the out put shows red/green but again if user just at the same moment click the another options it shifts ,  this should happen as user can only select one option at a time...

click [https://youtu.be/IQGea8tTvG8](Here) to see the video #goodfirstissue
The changes should be made in QuizPanel.kt

**Comment by ghost** [comment]
Hi @Rohit-554, please checkout [my PR](#2).

**Comment by Rohit-554** [comment]
ThankYou !! Problem is Resolved
